language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y git
script:
 - git config --global user.email "you@example.com"
 - git config --global user.name "Your Name"
 - logic/subuserCommands/test.py --travis